name: 0-webhook-signing-and-retry

services:
  receiver-mock:
    image: starciacademy/system-design-webhook-signing-and-retry-receiver-mock:latest
    container_name: 0-webhook-signing-and-retry-receiver-mock
    environment:
      - PORT=3000
      - WEBHOOK_SECRET=shared-secret-demo
      - TIMESTAMP_SKEW_SECONDS=300
    networks:
      - 0-webhook-signing-and-retry-network

  emitter:
    image: starciacademy/system-design-webhook-signing-and-retry-emitter:latest
    container_name: 0-webhook-signing-and-retry-emitter
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - WEBHOOK_SECRET=shared-secret-demo
      - MAX_ATTEMPTS=3
      - BACKOFF_MS=1000,3000,9000
    depends_on:
      - receiver-mock
    networks:
      - 0-webhook-signing-and-retry-network

networks:
  0-webhook-signing-and-retry-network:
    name: 0-webhook-signing-and-retry-network
